### ISSUE TITLE
Can't load analyze_tagger_coverage with a ConllChunkCorpusReader

### ISSUE THREAD

**Issue by ptnplanet** [japerk/nltk-trainer#2]
The ConllChunkCorpusReader needs an extra argument, a list of nodetags.

  File "analyze_tagger_coverage.py", line 47, in <module>
    corpus = reader_cls(args.corpus, '.+')
TypeError: **init**() takes at least 4 arguments (3 given)

**Comment by japerk** [comment]
@sbrugman Yes, it looks like the [ConllChunkCorpusReader](http://www.nltk.org/_modules/nltk/corpus/reader/conll.html) requires a chunk_types argument. The simplest fix would be to create a wrapper class you can use as the reader class.
