### ISSUE TITLE
requirements.txt might install nltk 3.x

### ISSUE THREAD

**Issue by marcelchastain** [japerk/nltk-trainer#27]
in requirements.txt, the line:
`nltk>=2.0b8`
might lead to nltk 3.x being installed, which is different from the requirements stated in the README (and has caused problems for my code personally).

Recommended that we set an upper limit with something like this:
`nltk>=2.0b8,<=2.9.9`

**Comment by Dauth** [comment]
can this be used with nltk 3?

**Comment by japerk** [comment]
Yes, nltk-trainer has been updated to be compatible with NLTK 3. But if you have any problems, please open an issue.
