### ISSUE TITLE
Memory Problem

### ISSUE THREAD

**Issue by nedhulton** [japerk/nltk-trainer#31]
I have a corpus of 70,000 documents (roughly 237MB) I keep getting hit with memory-related error messages.
I tried renting a VPS with 100 Gigs of RAM, but I got the same error messages. 
Is there a way to make the process less memory-intensive?
Is it possible to break the corpus up into smaller corpora, train multiple classifiers and then combine them into one large classifier?

**Comment by lababidi** [comment]
What is the command and parameters you are using? Any additional details
would be helpful to reproduce this.

**Comment by nedhulton** [comment]
Thank you for your fast response. I really appreciate it. I simply went for the following:
C:\...python C:..train_classifier.py movie_reviews --instances files --fraction 0.75 --no-pickle --min_score 2 --classifier NaiveBayes --show-most-informative 10

**Comment by japerk** [comment]
I'd suggest trying a scikit-learn classifier, like LogisticRegression, and perhaps not doing --min_score 2. Depends on when in the process the memory error happens.

**Comment by nedhulton** [comment]
Here is the full error message:


loading googleNews
2 labels: [u'neg', u'pos']
Traceback (most recent call last):
  File "C:\Users\ned\Desktop\sentiment\nltk-trainer-master\train_classifier.py",
 line 273, in <module>
    instances = [i for i in instances if i]
  File "C:\Users\ned\Desktop\sentiment\nltk-trainer-master\train_classifier.py",
 line 272, in <genexpr>
    instances = (norm_words(i) for i in lif(categorized_corpus, label))
  File "C:\Users\ned\Desktop\sentiment\nltk-trainer-master\train_classifier.py",
 line 215, in norm_words
    return functools.reduce(operator.add, [words if n == 1 else list(ngrams(word
s, n)) for n in args.ngrams])
MemoryError

**Comment by japerk** [comment]
That last line shouldn't execute if you don't use the --ngrams argument. Try running without that.

**Comment by nedhulton** [comment]
Unfortunately I get the same error message even without ngrams. What would you do if you were in my shoes? Is it possible to break up the corpus into several smaller corpora, train multiple classifiers and then combine them? Would that work?Thanks again for your help. 

Date: Mon, 24 Aug 2015 16:02:14 -0700

**Comment by riatzukiza** [comment]
the classifiers are statistical models, basicly just numbers. It would be possible, as you suggest, to create several smaller corpora and combine them, I wouldn't exactly know how to do this for this environment, I don't program python and am not really familiar with this library, I only know the math.

In terms of just the math, it would be a matter of going over every entry in each classifier and taking the average of the overlaps. As long as all the probabilities sum to 1, you end up with a valid model.

**Comment by japerk** [comment]
Multiple classifiers could certainly work. Slice up the corpus, train a classifier on each slice, and then you could combine the classifiers in a max-vote style, or average the probabilities using prob_classify.

**Comment by lababidi** [comment]
Did you try using the Scikit-learn based classifier? I _only_ use those as
the underlying classifieds as they are much more efficient in memory and
speed.

**Comment by lababidi** [comment]
make sure you have scikit-learn installed. Try of the option:
```train_classifier.py --classifier sklearn.MultinomialNB```
