### ISSUE TITLE
No Generated Pickle While Using Cross Validation

### ISSUE THREAD

**Issue by vexenta** [japerk/nltk-trainer#33]
I want to pickle my trained classifier, but I don't get any pickled classifier when I use --cross-fold option.

> python train_classifier.py --algorithm NaiveBayes --instances sents --fraction 0.9 --cross-fold 10 --show-most-informative 10 /mycorpuspath/

It shows the cross validation results without pickled file. If I remove --cross-fold option, the pickled file is generated.

How can I get the the cross-validated classifier? Thanks.

**Comment by japerk** [comment]
It doesn't really make sense to save a cross-validated classifier, because you're training on a different subset of data each time. So which classifier would you save?
If you want to train a classifier on all the data, you can use --fraction 1.0
